### ISSUE TITLE
TypeError when exporting MAL

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#24] opened 2020-01-28 16:20 UTC
I have 9 pages of follows, it seems after some time I randomly get this error:
`TypeError: /'csrf_token'\scontent='(.{40})'/.exec(...) is null` (on `Options.js:1:39394`)
Executed three times already, got it on different Manga each time.

**Comment by Glagan** [comment] 2020-01-28 22:18
It may be because sometimes MyAnimeList have random 500 error or the page take more than 30s (it's a problem on their end).  
I'll look at it and add a retry with a timer or something like that.

**Comment by Glagan** [comment] 2020-01-29 00:07
This should be fixed in the last release, I set a bigger timer between requests (The whole operation will be longer) and if it fails it should retry up to 3 times.
If it works you can close this.

It should already be up on both Chrome and Firefox.

**Comment by cpiber** [comment] 2020-01-29 07:23
"There was an error while receiving info from MyAnimeList, aborting." after two tries.
Also, that text is white on white, please check the colors.
Nice touch with the abort button though ;) But when the process is aborted, the button doesn't reset and clicking it just changes it to "Aborting...", does nothing.

Failing requests:
```
08:13:30.779 XHRGEThttps://myanimelist.net/ownlist/manga/add?selected_manga_id=98607
[HTTP/2 403 Forbidden 193ms]

Request URL:https://myanimelist.net/ownlist/manga/add?selected_manga_id=98607
Request Method:GET
Remote Address:54.149.194.237:443
Status Code:
403
Version:HTTP/2
	
Response Headers (147 B)	
Raw Headers
content-length	
134
content-type	
text/html
date	
Wed, 29 Jan 2020 07:13:30 GMT
server	
awselb/2.0
X-Firefox-Spdy	
h2
Request Headers (429 B)	
Raw Headers
Accept	
*/*
Accept-Encoding	
gzip, deflate, br
Accept-Language	
en,en-US;q=0.5
Connection	
keep-alive
Cookie	
MALSESSIONID=oqpt8hg5eidm74fsp…_gdpr_mdl_2=1; is_logged_in=1
DNT	
1
Host	
myanimelist.net
TE	
Trailers
User-Agent	
Mozilla/5.0 (X11; Ubuntu; Linu…) Gecko/20100101 Firefox/72.0
```

```
08:13:32.023 XHRGEThttps://myanimelist.net/ownlist/manga/98607/edit?hideLayout
[HTTP/2 403 Forbidden 193ms]

Request URL:https://myanimelist.net/ownlist/manga/98607/edit?hideLayout
Request Method:GET
Remote Address:54.149.194.237:443
Status Code:
403
Version:HTTP/2
	
Response Headers (147 B)	
Raw Headers
content-length	
134
content-type	
text/html
date	
Wed, 29 Jan 2020 07:13:32 GMT
server	
awselb/2.0
X-Firefox-Spdy	
h2
Request Headers (449 B)	
Raw Headers
Accept	
*/*
Accept-Encoding	
gzip, deflate, br
Accept-Language	
en,en-US;q=0.5
Cache-Control	
max-age=0
Connection	
keep-alive
Cookie	
MALSESSIONID=oqpt8hg5eidm74fsp…_gdpr_mdl_2=1; is_logged_in=1
DNT	
1
Host	
myanimelist.net
TE	
Trailers
User-Agent	
Mozilla/5.0 (X11; Ubuntu; Linu…) Gecko/20100101 Firefox/72.0
```

```
08:13:33.305 XHRGEThttps://myanimelist.net/ownlist/manga/98607/edit?hideLayout
[HTTP/2 403 Forbidden 192ms]

Request URL:https://myanimelist.net/ownlist/manga/98607/edit?hideLayout
Request Method:GET
Remote Address:54.149.194.237:443
Status Code:
403
Version:HTTP/2
	
Response Headers (147 B)	
Raw Headers
content-length	
134
content-type	
text/html
date	
Wed, 29 Jan 2020 07:13:33 GMT
server	
awselb/2.0
X-Firefox-Spdy	
h2
Request Headers (449 B)	
Raw Headers
Accept	
*/*
Accept-Encoding	
gzip, deflate, br
Accept-Language	
en,en-US;q=0.5
Cache-Control	
max-age=0
Connection	
keep-alive
Cookie	
MALSESSIONID=oqpt8hg5eidm74fsp…_gdpr_mdl_2=1; is_logged_in=1
DNT	
1
Host	
myanimelist.net
TE	
Trailers
User-Agent	
Mozilla/5.0 (X11; Ubuntu; Linu…) Gecko/20100101 Firefox/72.0
```

**Comment by Glagan** [comment] 2020-01-29 10:35
Yes, aborting while it failed didn't update the button and I used the wrong CSS class, it's fixed.  
For the real problem, I don't see anything wrong at all in the request you sent and yet you get a 403 Forbidden.

Are you using containers ? If you are, you need to be logged in on the *main* container.

I can't reproduce this issue at all... Can you access these pages on your own or do you also get a 403 ?

**Comment by cpiber** [comment] 2020-01-29 13:15
I don't think I am using containers, I have no idea what they are.
I'll be able to check in a few hours.

**Comment by cpiber** [comment] 2020-01-29 15:52
Tried again today, two times, both without error. Also doesn't seem to be a problem of other tabs using the network/unloading, tried that too. I'm confused.

**Comment by Glagan** [comment] 2020-01-29 17:32
What were the last lines in the output ?

**Comment by cpiber** [comment] 2020-01-29 17:53
"Done fetching MangaDex follow manga."
"Done, for real !"
That was the third time without problems, by the way.

**Comment by Glagan** [comment] 2020-01-29 18:01
So it worked, everything is fine then I guess, I can't reproduce it and I don't see where that would come from.

**Closed** 2020-01-29 18:28 UTC
